{% set name = "peppy" %}
{% set version = "0.31.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f8b19ca3e034afea77aa11d2b8d30982adc4b0ce44bae6d8ecd5cf0da0af002

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<3.10
  run:
    - attmap >=0.12.5
    - python >=3.6,<3.10
    - pyyaml >=5
    - ubiquerg >=0.5.2
    - pandas >=0.24.2
    - logmuse >=0.2

test:
  imports:
    - peppy

about:
  home: https://github.com/pepkit/peppy/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Project metadata manager for PEPs in Python

extra:
  recipe-maintainers:
    - stolarczyk
